name: Code Exchange Submission
description: Created content or code around Temporal? Tell us about it!
title: "[Submission] YOUR PROJECT / USE CASE HERE"
labels: ["code exchange submission", "triage"]
assignees:
- webchick
body:
  - type: markdown
    attributes:
      value: Hello World!
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: ex. https://github.com/myname/foo
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language is your project written in?
      options:
        - (please select)
        - .NET
        - Go
        - Java
        - PHP
        - Python
        - Ruby
        - TypeScript
        - Other / Unofficial SDK
      default: 0
  - type: textarea
    id: short-description
    attributes:
      label: Short description (max 256 chars)
      description: What's the "elevator pitch" for your project, and why it is useful to Temporal users?
      validations:
        required: true
