name: Code Exchange Suggestion
description: "Is there a use case or code sample you'd like to see covered? Let us know!"
title: "[Suggestion] DESIRED PROJECT / USE CASE HERE"
labels: ["code exchange suggestion", "triage"]
body:
  - type: markdown
    attributes:
      value: "Have a great idea that you don't currently see on [Code Exchange](https://temporal.io/code-exchange)? Tell us about it!"
  - type: textarea
    id: short-description
    attributes:
      label: Short description
      description: "What's the 'elevator pitch' for your project, and why it is useful to Temporal users?"
    validations:
      required: true
  - type: textarea
    id: pre-existing
    attributes:
      label: Existing material
      description: "Are you aware of any existing code, content, etc. that could be used to get someone started?"
