name: Code Exchange Submission
description: Created content or code around Temporal? Tell us about it!
title: "[Submission] YOUR PROJECT / USE CASE HERE"
labels: ["code exchange submission", "triage"]
assignees:
- webchick
body:
  - type: markdown
    attributes:
      value: "Thank you so much for offering to submit your code to [Code Exchange](https://temporal.io/code-exchange)! Please tell us a bit more about your project."
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: ex. https://github.com/myname/foo
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language is your project written in?
      options:
        - (please select)
        - .NET
        - Go
        - Java
        - PHP
        - Python
        - Ruby
        - TypeScript
        - Other / Unofficial SDK
      default: 0
    validations:
      required: true
  - type: textarea
    id: short-description
    attributes:
      label: Short description (max 256 chars)
      description: What's the "elevator pitch" for your project, and why it is useful to Temporal users?
    validations:
      required: true
  - type: textarea
    id: long-description
    attributes:
      label: Long Description
      description: "Go into more detail; what's your project about? What types of problems does it solve? Are there screenshots / videos? etc. This is rich text, so go nuts! :)"
    validations:
      required: true
  - type: textarea
    id: author
    attributes:
      label: Author(s)
      description: How author(s) would like to be credited on this submission.
      placeholder: Name / Company / link to headshot 
    validations:
      required: true
